POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
    "title": "Final Fnatsy VII",
    "author": "Square Enix",
    "url": "square-enix.com/final-fantasy-vii",
    "likes": 7777
}